version: 2
updates:
  # Keep Dockerfile base images up to date
  - package-ecosystem: "docker"
    directory: "/" # Path where your Dockerfile lives
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(docker)"

  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "deps(actions)"
